[project]
name = "echonotify"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiokafka>=0.12.0",
    "celery>=5.5.3",
    "fastapi>=0.121.1",
    "redis>=7.0.1",
    "uvicorn>=0.38.0",
    "websockets>=15.0.1",
]
