name: CI

on:
  push:
    branches: [master, develop, 'feature/*', 'hotfix/*', 'fix/*']
  pull_request:
    branches: [master, develop, 'feature/*', 'hotfix/*', 'fix/*']

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Install Python 3.13.1 and set up environment
        run: |
          uv python install 3.13.1
          uv python pin 3.13.1
          uv python update-shell

      - name: Install deps
        run: uv sync --locked --all-extras --dev

      - name: Black
        run: uv run black --check src

      - name: Ruff
        run: uv run ruff check src

      - name: Flake8
        run: uv run flake8 src --count --show-source --statistics --ignore=E501,W503

  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Install Python 3.13.1 and set up environment
        run: |
          uv python install 3.13.1
          uv python pin 3.13.1
          uv python update-shell

      - name: Install deps
        run: uv sync --locked --all-extras --dev

      - name: Create .env
        run: printf '%s\n' "${{ secrets.DOTENV_FILE }}" > .env

      - name: Run tests
        run: uv run pytest

  notify:
    needs: [lint, test, docker]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Decide status
        id: status
        run: |
          if [ "${{ needs.lint.result }}" = "success" ] && \
             [ "${{ needs.test.result }}" = "success" ] && \
             [ "${{ needs.docker.result }}" = "success" ]; then
            echo "msg=✅ CI успешно завершён" >> $GITHUB_OUTPUT
          else
            echo "msg=❌ CI провалился" >> $GITHUB_OUTPUT
          fi

      - name: Telegram notify
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{ steps.status.outputs.msg }}
            Репо: ${{ github.repository }}
            Лог:  https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
